### ISSUE TITLE
開催する場について

### ISSUE THREAD

**Issue by kozo2** [PyDataOsaka/pydata-osaka-2016#1]
梅田が望ましい
- 神戸在住で興味を持っている方を数名確認

思い当たる先
- 市民会館
- データサイエンスに熱心な会社

具体的な場所
- 大阪市立生涯学習センター http://osakademanabu.com/umeda/access-map

**Comment by wrist** [comment]
市民会館、大阪市立生涯学習センターは過去に使ったことがありますが、梅田近辺となると後者になるかと思います。後者は会員登録するとWebから空き情報の検索および予約が出来たはずですが、安価で使用できるため割と人気なので押さえるとなると数カ月前から動く必要があるかと思います。

他の案として
- [イノベーションハブ](http://www.innovation-osaka.jp/ja/)の[Osaka Hackers Club](http://www.innovation-osaka.jp/ja/ohc)

というものがあります。プレーヤーとして登録(確か要面接)するとグランフロントのスペースがイベントで使えるようになるため、選択肢としてありかもしれません。

いずれにせよ
- 開催目標日
- 会場サイズ
- 収容可能人数
- その他条件(プロジェクタ使用必須、など)

をまずある程度定めた上で、会場を探す流れになるのかと思います。

**Comment by kozo2** [comment]
https://pydata-jp.slack.com/ でのやりとりがほとんどでしたが

10月30日に https://www.oit.ac.jp/umekita/ でfix

**Comment by kozo2** [comment]
プロジェクタやケーブルなどの担当分け

担当 | 担当者
 --- | ---
予備プロジェクタ | yokmama
プロジェクタ用変換コネクタ・ケーブル | kozo2
 | 
 |
