### ISSUE TITLE
#1の発表集め

### ISSUE THREAD

**Issue by kozo2** [PyDataOsaka/pydata-osaka-2016#3]
http://www.meetup.com/PyData-Osaka/events/233759282/
での発表者を募集しています.
ご興味お持ちの方はコメントください．
- 基本的にはNUMFOCUS の sponsored project の使い方、活用例などの発表をお願いしたい
- 上記以外でもData解析に関することであれば何でもOK．Pythonにも限定しません
### スケジュール

| 発表内容 | 発表者 | 時間見積 |
| --- | --- | --- |
| PyDataとNumFOCUSの紹介 | kozo2 | 10分 |
| Bash on Ubuntu on WindowsでJupyter Notebookを使おう | kozo2 | 10分 |
| Rubyでデータ解析 | genya0407 | 10分 |
| NetworkXによるグラフの分析と可視化 | likr | 15 ~ 30分 |
| 休憩 |  | 10分 |
| IPython(Jupyter)の最近の動向について | wrist | 45分 |
| Introduction to PyMC3 | taku-y | 30分 |
| Ruby界から見たscikit-learnの長所 | kozo2 | 15分 |

**Comment by kozo2** [comment]
@kozo2 @likr @genya0407 @wrist の発表を追加しました。
ほぼほぼ出た感じなのでとりあえずcloseします

**Comment by kozo2** [comment]
https://github.com/PyDataOsaka/pydata-osaka-2016/tree/master/meetup1
へJupyter Notebookが追加されるまでopenにしておくことにしました。

**Comment by taku-y** [comment]
遅くなりましたが、もし時間があれば発表を希望します。タイトルは"Introduction to PyMC3"です。スライドは[こちら](https://github.com/taku-y/presentation/tree/master/20161030-pydata-osaka)です。スライド全部を発表すると時間が足りないと思うので、適当に調整します。時間が無ければ次回発表します。ご検討よろしくお願い致します。

**Comment by kozo2** [comment]
@taku-y ご連絡ありがとうございます。ぜひご発表をお願い致します。
https://github.com/taku-y/presentation/tree/master/20161030-pydata-osaka の資料承知しました．
時間にはあまり固くなりたくないと思っているのですがどれくらいをお考えでしょうか．
特にけずっていただかなくても収まるのではないかと思っています．

**Comment by taku-y** [comment]
@kozo2 連絡が遅くなったのにも関わらず、ご了承頂いてありがとうございます。スライドを全部発表する場合、30分程度と考えております。

**Comment by kozo2** [comment]
- [ ] YouTubeで発表内容の保存

**Comment by kozo2** [comment]
「Ruby界から見たscikit-learnの長所」はまたの機会へ持ちこし，となりました
