### ISSUE TITLE
#2の発表集め

### ISSUE THREAD

**Issue by kozo2** [PyDataOsaka/pydata-osaka-2016#6]
no.2では Project Jupyter をテーマとしています．

発表ご希望の方はcommentをお願いします．
(テーマと異なっていても構いません)

1. @kozo2 binder の紹介
2. @kozo2 Jupyter Newsletter を見てみよう
3. @kozo2 airbnb の knowledge-repo の紹介
4. @genya0407  nteract の紹介
5. @taku-y PyMC3の変分ベイズの話
6. @kozo2 Osaka.Stanに行ってきた話 
7. @hkwi Civic HackにJupyterを

**Comment by taku-y** [comment]
テーマと外れるのですが、PyMC3の変分ベイズの話をしてもよろしいでしょうか。

**Comment by kozo2** [comment]
@taku-y はい．是非お願いします．

**Comment by taku-y** [comment]
ご了承頂いてありがとうございます。

**Comment by hkwi** [comment]
私も http://hkwi.github.io/kobe-barcelona/ で jupyter を使った話をしてみたいです。

**Comment by kozo2** [comment]
@hkwi はい，是非お願いします．
お話しいただく内容にタイトルをいただけますでしょうか

**Comment by hkwi** [comment]
"Civic HackにJupyterを"でお願いします！

**Comment by kozo2** [comment]
@hkwi このissueにはタイトルを反映させてもらったのですが，meetupのページの方はすでに開催中のものは編集ができませんでした．申し訳ありません． 
https://medium.com/pydata-osaka
には反映させますのでご了承ください
